### PR TITLE
Upgrade to egui 0.20

### PR DESCRIPTION
**Pull request by tonogram**
Pretty much just a drop-in replacement. Tested on my own plugin, LGTM.

### CODE REVIEW

**Comment by Aries85** [comment]
@BillyDM Would it be possible to merge it?

Tried a GUI with it and it seems fine.

**Comment by tonogram** [comment]
Honestly, I suppose I ought to bump this up to 0.21 before this gets merged anyway.

**Comment by Aries85** [comment]
Sure, why not 👍

**Comment by BillyDM** [comment]
closing because of https://github.com/BillyDM/egui-baseview/pull/15

**Pull request closed without merging**
